#!/usr/bin/env groovy
def APP_NAME
def APP_VERSION
def DOCKER_IMAGE_NAME
def PROD_BUILD = false

pipeline {
  agent any
  environment {
    // Credentials ID에 맞춰서 설정
    DOCKERHUB_CREDENTIALS = 'docker-hub-credentials'
    IMAGE_NAME = 'bokjunsoo/spark-app'
    IMAGE_TAG = "v${env.BUILD_NUMBER}"
  }
  stages {
    
    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    stage('Build Image') {
      steps {
        script {
          docker.build("${IMAGE_NAME}:${IMAGE_TAG}")
        }
      }
    }

    stage('Push to Docker Hub') {
      steps {
        script {
          docker.withRegistry('https://registry.hub.docker.com', DOCKERHUB_CREDENTIALS) {
            docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push()
            // latest 태그 추가로 편의성 up
            docker.image("${IMAGE_NAME}:${IMAGE_TAG}").push('latest')
          }
        }
      }
    }
  }
  post {
    success {
      echo "Image pushed: ${IMAGE_NAME}:${IMAGE_TAG}"
    }
    failure {
      echo "Build or push failed."
    }
  }
}

